# Generated by Django 3.0.5 on 2020-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_descripion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_descripion',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
